### ISSUE TITLE
Port 9090 taken by tcp on Debian Jessie

### ISSUE THREAD

**Issue by nevenjovanovic** [Leipzig-Furman-Plutarch/virtualMachine2016#1]
Trying to follow the instructions, after "vagrant up", I got this warning: "Vagrant cannot forward the specified ports on this VM, since they would collide with some other application that is already listening
on these ports. The forwarded port to 9090 is already in use on the host machine.". On my machine (Debian Jessie, AMD 64) netstat says that tcp and tcp6 are listening on port 9090. I can change the port in the Vagrantfile easily, but I don't know whether I'll break something else by doing so. What do you think?
(I have also tried vagrant reload, as was recommended in the error message, and got the same message, ending with "Sometimes, Vagrant will attempt to auto-correct this for you. In this case, Vagrant was unable to. This is usually because the guest machine is in a state which doesn't allow modifying port forwarding. You could try 'vagrant reload' (equivalent of running a halt followed by an up) so vagrant can attempt to auto-correct this upon booting)".

**Comment by Eumaeus** [comment]
I've run into that, too. Can you try changing the default port in your Vagrant file, and see if it works? Then I can try it, locally, and perhaps we can settle on free ports that work for everyone. Thank you SO MUCH for identifying this problem and sharing it!

**Comment by nevenjovanovic** [comment]
After chaning the port to 9099, I got the following message: "The guest machine entered an invalid state while waiting for it to boot. Valid states are 'starting, running'. The machine is in the 'poweroff' state. Please verify everything is configured properly and try again.

If the provider you're using has a GUI that comes with it, it is often helpful to open that and watch the machine, since the GUI often has more helpful error messages than Vagrant can retrieve. For example, if you're using VirtualBox, run `vagrant up` while the VirtualBox GUI is open. The primary issue for this error is that the provider you're using is not properly configured. This is very rarely a Vagrant issue."

Will try it now with VirtualBox GUI open.

**Comment by nevenjovanovic** [comment]
After trying to start the machine via VirtualBox GUI, I get the following message:
"Failed to open a session for the virtual machine virtualMachine2016_default_1467402160741_84490.

AMD-V is disabled in the BIOS (or by the host OS). (VERR_SVM_DISABLED).

Result Code: NS_ERROR_FAILURE (0x80004005)
Component: Console
Interface: IConsole {8ab7c520-2442-4b66-8d74-4ff1e195d2b6}".

**Comment by nevenjovanovic** [comment]
Now I removed the machine and repeated the "vagrant up", but got the same VirtualBox error message as above in the end (AMD-V is disabled... etc).

**Comment by Eumaeus** [comment]
Neven... this is a matter of changing the BIOS setting, which is specific to your machine. You should be able to find instructions for your brand and model online. Every brand of machine does it differently. You need to turn AMD-V _on_, reboot, and try the VM. 

For the other issue, I've found that if Vagrant tries and fails to start, it gets in a confused state. Either finding all the "ruby" and "virtual box" processes left running, and killing them, can help. Or (the extreme option), a reboot and re-clone of the VM's repo.

**Comment by nevenjovanovic** [comment]
Chris, AMD-V did the trick. The machine is up and pulling packages as we speak; so far, so good.

**Comment by Eumaeus** [comment]
Yes!!!!

**Comment by nevenjovanovic** [comment]
Executed successfully script 7 (Setup Apache2). One remark, and one question. Remark: after Apache is reconfigured and SPARQL server restared with script 6, I am not able to access the server at (in my case) localhost:9099/sparqlcts anymore; Jetty reports that there is nothing there, and I can only use the address http://192.168.33.10/cts as described on the README page. Question: how do I undo changes to Apache done with the script 7 -- without the nuclear option of destroying the whole virtual machine?

**Comment by Eumaeus** [comment]
In the VM, you can:

`cd /etc/apache2/sites-available/`
'sudo rm cite.conf`
`sudo apacheclt restart`

That should do it. You can also look at the "cite.conf" file, and change the port values in that. `apachectl restart` will put the changes into effect.
