### ISSUE TITLE
8_Build_Template_Data.sh - Java heap space issue?

### ISSUE THREAD

**Issue by nevenjovanovic** [Leipzig-Furman-Plutarch/virtualMachine2016#3]
With a repository containing 216 TEI XML files (2.8 MB in all), described as CTS in the `citationconfig.xml` and the `inventory.xml` in the `cts-corpus-template` directory, from the virtual machine I am running the `8_Build_Template_Data.sh` script. The script progresses to the point where there seems to be some problem with Java heap space:

<code>
Make file for cts.ttl in /vagrant/citemgr/projects/build/ttl

:projects:ctsttl FAILED

FAILURE: Build failed with an exception.
- What went wrong:

Execution failed for task ':projects:ctsttl'.

> Java heap space

</code>

If Java is the issue, how do I increase heap space, and where?

**Comment by Eumaeus** [comment]
in /vagrant/citemgr, I added a file named gradle.properties, which sets a higher amount for Java memory.  In the VM, if you run the "00_…" script, it will pull down that change. Try running the "8_" script again with this configuration, and we'll see if it helps.

**Comment by Eumaeus** [comment]
If you get that heap space error again, it would be helpful to see the terminal output leading up to it, so we can see at what state in the process it is running out of memory.

**Comment by nevenjovanovic** [comment]
@Eumaeus , this time the script / build completed without errors. Something strange happened, however -- everything from the `scripts` directory had been deleted. Also, there was some strange output when I ran the `00_Housekeeping` script. Here is the output from my terminal:
<code>

## vagrant@vagrant-ubuntu-trusty-32:/vagrant/scripts$ 00_Housekeeping.sh

## Housekeeping: Updating all Git repositories…

The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Already up-to-date.
remote: Counting objects: 3, done.
remote: Total 3 (delta 1), reused 1 (delta 1), pack-reused 2
Unpacking objects: 100% (3/3), done.
From https://github.com/cite-architecture/citemgr
   f64bfa0..7d24c25  master     -> origin/master
Updating f64bfa0..7d24c25
Fast-forward
 gradle.properties | 3 +++
 1 file changed, 3 insertions(+)
 create mode 100644 gradle.properties

## Already up-to-date.

vagrant@vagrant-ubuntu-trusty-32:/vagrant/scripts$ 8_Build_Template_Data.sh

</code>

Then, after the script `8_Build_Template_Data` was completed:

<code>
Make file for cts.ttl in /vagrant/citemgr/projects/build/ttl

BUILD SUCCESSFUL

## Total time: 3 mins 43.915 secs

Copying the resulting file, 'corpus.tll', into 'vagrant/data/' as 'cts-template.ttl', for safekeeping.

---

Moving the TextInventory file cataloging this test data into place.

---

Done!

## vagrant@vagrant-ubuntu-trusty-32:/vagrant/scripts$ 9_Load_Template_Data_into_DB.sh

Navigate to where Gradle/Fuseki stores data files, specifically the 'cts' data…

## /vagrant/scripts/9_Load_Template_Data_into_DB.sh: line 7: cd: /vagrant/cs2/fuseki/fusekibase/databases/cts: No such file or directory

Remove anything there, since we are loading new data…

---

Use the 'tdbloader2' utility from Apache Jena to load our 'cts-template.ttl' file into a TDB Database…

Resolved symbolic links for JENA_HOME to /usr/bin/apache-jena-3.1.0
 19:34:40 INFO -- TDB Bulk Loader Start
mkdir: cannot create directory ‘/vagrant/cs2/fuseki/fusekibase/databases/cts’: No such file or directory

##  19:34:40 ERROR Failed during data phase

Done! The CTS Template data has been loaded.
Re-run the scrdipt '6_Run SparqlCTS.sh' to configure the service and run it with the new data.
vagrant@vagrant-ubuntu-trusty-32:/vagrant/scripts$ ls
vagrant@vagrant-ubuntu-trusty-32:/vagrant/scripts$ 
vagrant@vagrant-ubuntu-trusty-32:/vagrant/scripts$ ls -al

</code>

There was no script to run! Git reports this:

<code>

deleted:    scripts/00_Housekeeping.sh
deleted:    scripts/0_Configure_CS2.sh
deleted:    scripts/1_Build_Test_Data.sh
deleted:    scripts/2_Load_Test_Data_into_DB.sh
deleted:    scripts/3_Test_CTS.sh
deleted:    scripts/4_Build_Demo_Data.sh
deleted:    scripts/5_Load_Demo_Data_into_DB.sh
deleted:    scripts/6_Run_SparqlCTS.sh
deleted:    scripts/7_Set_Up_Apache2.sh
deleted:    scripts/8_Build_Template_Data.sh
deleted:    scripts/9_Load_Template_Data_into_DB.sh
deleted:    scripts/Links.html
deleted:    scripts/apache2-cite-proxy.conf
deleted:    scripts/citemgr-cts-demo.gradle
deleted:    scripts/citemgr-cts-template.gradle
deleted:    scripts/citemgr-cts-test.gradle
deleted:    scripts/cts-demo.sh

</code>

**Comment by Eumaeus** [comment]
Yikes. I think Script 9 did that. The "rm *" is of course a terrible idea. You can get the contents of /vagrant/scripts back by cloning the VM anew, and copying those over. But I need to fix this so it never happens again.

**Comment by nevenjovanovic** [comment]
No problem, I reverted the uncommitted changes with `git checkout -- scripts/*`, and a new build is being prepared as we speak. What should be changed in the script 9?

**Comment by Eumaeus** [comment]
In Script 9, there is the line:

`cd /vagrant/cs2/fuseki/fusekibase/databases/cts`

For some reason, that was unsuccessful. Then the next line is:

`rm *`

Which is supposed to clear out the /databases/cts directory, but actually deleted everything in the /scripts/ directory. I am not sure why that happened.

I am going to replace that dangerous line with specific commands to delete the DB files that are actually there, so if the command is run from the wrong place, it won't do any harm.

**Comment by Eumaeus** [comment]
I have pushed a new version of Script 9. It is now much less dangerous. See if the sequence:

00_
8_
9_
6_

works.

**Comment by nevenjovanovic** [comment]
Actually, it seems that for some reason Fuseki is not present in my virtual machine. I have tested it by running scripts 1,  2 -- and the same problem occurred:

<code>

## vagrant@vagrant-ubuntu-trusty-32:/vagrant/scripts$ 2_Load_Test_Data_into_DB.sh

Navigating to where Gradle/Fuseki stores data files, specifically the 'ctsTest' data…

## /vagrant/scripts/2_Load_Test_Data_into_DB.sh: line 6: cd: /vagrant/cs2/fuseki/fusekibase/databases/ctsTest: No such file or directory

Removing anything there, since we are loading new data…

---

Using the 'tdbloader2' utility from Apache Jena to load our 'cts-test.ttl' file into a TDB Database…

Resolved symbolic links for JENA_HOME to /usr/bin/apache-jena-3.1.0
 20:06:47 INFO -- TDB Bulk Loader Start
mkdir: cannot create directory ‘/vagrant/cs2/fuseki/fusekibase/databases/ctsTest’: No such file or directory

##  20:06:47 ERROR Failed during data phase

Done!

</code>

I'll rebuild the machine and see what happens.

**Comment by Eumaeus** [comment]
Yep. At this point, that might be best. I will be offline until tomorrow, but report, if you can, and I'll keep trying to fix it up.

**Comment by nevenjovanovic** [comment]
It seems that somehow I've lost (or destroyed) Gradle scripts in the `/vagrant/cs2` directory. Script 0 is not successful, which is a bit harder to understand since it expects the tests to fail:

<code>

## vagrant@vagrant-ubuntu-trusty-32:/vagrant/scripts$ 0_Configure_CS2.sh

Navigating to the cs2 directory…

---

Making sure Gradle is working properly, and letting it download a million dependencies…

FAILURE: Build failed with an exception.
- What went wrong:
  Task 'clean' not found in root project 'cs2'.
- Try:
  Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

## Total time: 4.261 secs

Running the 'configure' task in Gradle to set up the Database…

FAILURE: Build failed with an exception.
- What went wrong:
  Task 'configure' not found in root project 'cs2'.
- Try:
  Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

## Total time: 4.311 secs

Creating an 'invs' directory where SparqlCTS can find text inventory files…

---

Navigating to the SparqlCTS directory…

---

Running the Integration Tests for SparqlCTS.

THESE WILL ALL FAIL! THERE IS NO DATA YET!

…but it will allow Gradle to set up the directory structure for the database.
(It will take some time to load, run, and fail all the tests.)

FAILURE: Build failed with an exception.
- What went wrong:
  Task 'farmIntegrationTest' not found in root project 'sparqlcts'.
- Try:
  Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

## Total time: 4.196 secs

## The 'FAIL' messages you see are okay! There is no data loaded yet, so of course they fail.

Done!

</code>

Thanks for your support!

**Comment by nevenjovanovic** [comment]
Yes, I've obviously messed things up by forking a repository and then, at some point, trying to revert the changes done after the `rm*`. In the repository which was cloned directly from your Github repo, everything works well, including the `00_Housekeeping` script. It seems to me that, in the next round, the process for adding own files to the `cts-corpus-template` directory should be clarified a bit.

**Comment by nevenjovanovic** [comment]
Ha! I have copied everything in the `cs2` repository back from the cloned Github repo, and now I have managed to get the CroALa CTS repository up and running.

![screenshot from 2016-07-03 23 19 31](https://cloud.githubusercontent.com/assets/5147578/16547664/7b89fba6-4175-11e6-8e1f-af1811c6b587.png)

(It turns out that I have a CTS issue, but I'll discuss that with @neelsmith ...)
