### ISSUE TITLE
"See text" for Valid References contains XML, but is only displayed as source (parsing error?)

### ISSUE THREAD

**Issue by nevenjovanovic** [Leipzig-Furman-Plutarch/virtualMachine2016#4]
I have built a collection using the cts-corpus-template. I get a list of valid URN references for my documents as expected. When I select the "see text" link, however, an empty page is displayed. It is not really empty, because when I inspect the source I see the XML that I expect. Perhaps this is just a setting in my browser (Chromium and Chrome both behave identically) -- but it could be a sign that an XSLT stylesheet is not working, or something.
Firefox is offended by the `tei:div type` not having any value (our original file has `<div type="poesis-epica-versio" met="hexameter">`):

```
XML Parsing Error: not well-formed
Location: http://localhost:9099/sparqlcts/api?request=GetPassagePlus&stylesheet=cts_passage&urn=urn:cts:croala:zamagna-b.osmanidos.croala-op:1
Line Number 14, Column 112:
<passage xml:lang="lat"><tei:TEI xmlns:tei='http://www.tei-c.org/ns/1.0'><tei:text><tei:body><tei:div type><cts:node xmlns:cts="http://chs.harvard.edu/xmlns/cts" urn="urn:cts:croala:zamagna-b.osmanidos.croala-op:1" passage="1">
```

**Comment by Eumaeus** [comment]
You can't use wild-cards in the citation-mapping. Some of that will (evidently) get past the various CTS utilities, but (obviously) it won't work. Solution: document the text specifically.
