### ISSUE TITLE
Parsing error prevents displaying text as HTML page because of an asterisk in the XPath

### ISSUE THREAD

**Issue by nevenjovanovic** [Leipzig-Furman-Plutarch/virtualMachine2016#7]
When I start the sparqlcts application and look at the valid references, a list of them is displayed. I can go as deep as I like. But when I select "see text" beside one of the references, the resulting page cannot be displayed (in Firefox and in Chrome) because of an XML Parsing Error: not well-formed. The offending part is the asterisk instead of the name of the element:

``` xml
<tei:text><tei:body><tei:div><tei:* n='p2'><tei:s n='s1'>
```

The asterisk was produced by the following line in the `citationconfig.xml`:

``` xml
<citationMapping>
      <citation label="sectio" scope="/tei:TEI/tei:text/tei:body/tei:div" xpath="/tei:*[@n='?']">
        <citation label="sententia" scope="/tei:TEI/tei:text/tei:body/tei:div/tei:*[@n='?']" xpath="/tei:s[@n='?']">
          <citation label="membrum" scope="/tei:TEI/tei:text/tei:body/tei:div/tei:*[@n='?']/tei:s[@n='?']" xpath="/tei:*[@n='?']"/>

        </citation>
      </citation>
    </citationMapping>
```

This expresion is valid for citemgr (or other CITE programs), however, and the database gets built without any complaints. So I guess the problem is in the XSLT stylesheet?

**Comment by Eumaeus** [comment]
This is why XML sucks ;-)

More seriously… this is not a CTS problem, but a data problem. The editor should *know* how the text is structured, and there should never be an "*" in the citation mapping. There must be *some* element there… name it!
